# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Prod tests and build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -Dmaven.test.failure.ignore=false clean install

    - name: Release on openshift
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: https://api.us-east-1.starter.openshift-online.com:6443/apis/build.openshift.io/v1/namespaces/drop-here-backend/buildconfigs/drop-here-backend/webhooks/a0f9bce0c3eaa884/github
        data: "Please build"
